### PR TITLE
fix: Fixes an issue where snyk csproj parser crashes when propertyGroup is missing from project file

### PR DESCRIPTION
**Pull request by Havunen**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?

This fixes an issue where snyk parser crashes cannot read "length" of undefined, it seems to me that logic was already handling the case where targetFrameworks returns empty array, but reading the property failed.

#### Where should the reviewer start?

Simple bug fix

#### How should this be manually tested?

Added unit test, but it can be manually tested as described in these Github issues: https://github.com/snyk/snyk-nuget-plugin/issues/103 https://github.com/snyk/snyk-nuget-plugin/issues/75

#### Any background context you want to provide?

-

#### What are the relevant tickets?

-

#### Screenshots

-

### CODE REVIEW

**Review by jan-stehlik — COMMENTED** [review]
<strike>Hey @Havunen , thanks a lot for your contribution :tada: :100:

In order to get this properly reviewed we need to:
1. create a PR from a branch in this repo, **not** it's fork. This is important so that we can run the code locally and review properly
2. Make sure all commit messages follow contribution [guidance](https://github.com/snyk/snyk-nuget-plugin/blob/master/.github/CONTRIBUTING.md#commit-types) (note `fix:` is meant to be lowercase)
3. Sign CLA agreement

Looking forward to get this reviewed and merged soon</strike>

Sorry for confusion, i don't think you will have write access to this repo, what you've done is great, we will review shortly

**Comment by Havunen** [comment]
This is the error snyk throws without the fix: 
```
Cannot read properties of undefined (reading 'length')
```

**Review by jan-stehlik — APPROVED** [review]
LGTM, welcome and thanks for you contribution @Havunen :tada: :100: 

can we make sure to use commit message according to our [standard](https://github.com/snyk/snyk-nuget-plugin/blob/master/.github/CONTRIBUTING.md#commit-types), note `fix: ` is all lowercase.

Thanks

**Comment by jan-stehlik** [comment]
Once merged and new version is published, don't forget to bump the library in [Snyk CLI](https://github.com/snyk/snyk/blob/4b8521a3a6d9ad4705f29efeb481714fda3dbd65/package.json#L128)

**Comment by Havunen** [comment]
> can we make sure to use commit message according to our standard, note fix: is all lowercase.

Yeah the commit starts with lower cased "fix: ", I also changed the PR title to start with lower cased fix. Am I missing something here?

**Comment by jan-stehlik** [comment]
> > can we make sure to use commit message according to our standard, note fix: is all lowercase.
> 
> Yeah the commit message starts with lower cased "fix: ", I also changed the PR title to start with lower cased fix. Am I missing something here?

All is great, thanks @Havunen :+1:

**Comment by Havunen** [comment]
@admons can you review this change please, would nice to get this fixed

**Review by tonidevine1 — APPROVED** [review]

**Pull request merged**
